### ISSUE TITLE
Approach API URL, not a JS object. Use Axios, not Supertest

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/nodejs-integration-tests-best-practices#55]
Approaching URL (with Axios for example) and not relating to 'app' object with supertest is better because:

* Not coupled to Express
* Much more popular
* Allows approaching remote servers as well (e.g. staging, production)

**Comment by mikicho** [comment]
@goldbergyoni 
I know this is not critical, but why `axios`?
I found [here](https://github.com/request/request/issues/3143) a list of alternatives.

More info:
- [npm trends](https://www.npmtrends.com/axios-vs-got-vs-node-fetch)
- synk report ([axios](https://snyk.io/advisor/npm-package/axios), [got](https://snyk.io/advisor/npm-package/got), [node-fetch](https://snyk.io/advisor/npm-package/node-fetch))

Maybe we should use `node-fetch` because it's more specific to node?

**Comment by goldbergyoni** [comment]
Axios has x10 more GitHub stars which tells much better about the community trust and popularity. npm downloads is misleading - You may reach to the top based on one person's decision.

Consequently, Axios eco-system is much bigger: If you search in GitHub for "axios" you'll get 26000 lib which has 'axios' in their title, some of them are plugins. Only 1500 are returned for node-fetch.

Practically, search for a circuit breaker or cache plugins - Axios has plugins with almost 1000 starts, the others plugins have almost no traction
